/**
 * Design system palette: OKLCH-derived stepped scales (0–9).
 * Source of truth: palette.json (generated by scripts/generate-palette.mjs).
 * Use for contrast tests and programmatic theme access.
 */

import palette from "./palette.json";

export type ScaleName = "gray" | "blue" | "green" | "amber" | "red" | "indigo";
export type Scale = readonly [string, string, string, string, string, string, string, string, string, string];

export const scales = palette as Record<ScaleName, string[]>;

/** Gray (neutrals), Blue (accent), Green/Amber/Red (status), Indigo (role: sales) */
export const gray: Scale = scales.gray as unknown as Scale;
export const blue: Scale = scales.blue as unknown as Scale;
export const green: Scale = scales.green as unknown as Scale;
export const amber: Scale = scales.amber as unknown as Scale;
export const red: Scale = scales.red as unknown as Scale;
export const indigo: Scale = scales.indigo as unknown as Scale;

export default scales;
