/**
 * Query expansion maps for product search (inspired by pasplv1).
 * Keys are lowercase; values are the expansion we substitute when normalizing the query.
 * Used so "actv brake", "splndr", "brek" etc. match items containing "activa", "splendor", "brake".
 */

const VEHICLES: Record<string, string> = {
  actv: 'activa',
  actva: 'activa',
  activahm: 'activa',
  actvhm: 'activa',
  activ: 'activa',
  dsvr: 'discover',
  dscvr: 'discover',
  disc: 'discover',
  discvr: 'discover',
  discovr: 'discover',
  dis100: 'discover 100',
  dis125: 'discover 125',
  dis150: 'discover 150',
  dis: 'discover',
  plsr: 'pulsar',
  pulsr: 'pulsar',
  puls: 'pulsar',
  plsdr: 'pulsar',
  shne: 'shine',
  shn: 'shine',
  spldnr: 'splendor',
  splndr: 'splendor',
  spldor: 'splendor',
  spldr: 'splendor',
  spld: 'splendor',
  splnd: 'splendor',
  pltna: 'platina',
  platna: 'platina',
  pltn: 'platina',
  plat: 'platina',
  pasn: 'passion',
  passn: 'passion',
  pssn: 'passion',
  ppro: 'passion pro',
  passpro: 'passion pro',
  apche: 'apache',
  apach: 'apache',
  apc: 'apache',
  rtr: 'apache rtr',
  glmr: 'glamour',
  glamr: 'glamour',
  glm: 'glamour',
  glmour: 'glamour',
  unicrn: 'unicorn',
  uncrn: 'unicorn',
  uni: 'unicorn',
  mstro: 'maestro',
  mestro: 'maestro',
  mastro: 'maestro',
  mst: 'maestro',
  juptr: 'jupiter',
  jptr: 'jupiter',
  jup: 'jupiter',
  hnd: 'honda',
  hnda: 'honda',
  hro: 'hero',
  bjj: 'bajaj',
  baj: 'bajaj',
  bj: 'bajaj',
  ymh: 'yamaha',
  ymha: 'yamaha',
  re: 'royal enfield',
  ktm: 'ktm',
  bllt: 'bullet',
  bullt: 'bullet',
  clssc: 'classic',
  clsic: 'classic',
  wgo: 'wego',
  ct: 'ct100',
  ct100: 'ct100',
  y2k: 'y2k',
  access: 'access 125',
  acc125: 'access 125',
  ntorq: 'ntorq 125',
  ntorq125: 'ntorq 125',
  // Compound vehicle abbreviations from real orders
  cddlx: 'cd deluxe',
  cdlx: 'cd deluxe',
  cddel: 'cd deluxe',
  cd100: 'cd 100',
  cd: 'cd deluxe',
  stnnr: 'stunner',
  stnr: 'stunner',
  tvstar: 'tvs star',
  xcd: 'xcd',
  fzs: 'fzs',
  fz: 'fz',
  r15: 'r15',
  duke: 'duke',
  dio: 'dio',
  navi: 'navi',
  grazia: 'grazia',
  burgman: 'burgman',
  avenger: 'avenger',
  avngr: 'avenger',
  dominar: 'dominar',
  dom: 'dominar',
  hunk: 'hunk',
  xtreme: 'xtreme',
  xtrm: 'xtreme',
  karizma: 'karizma',
  kzmr: 'karizma',
  cbz: 'cbz',
  cb: 'cb',
  trigger: 'trigger',
  livo: 'livo',
  hf: 'hf deluxe',
  hfdlx: 'hf deluxe',
  super: 'super splendor',
  ismart: 'ismart',
  raider: 'raider',
  radeon: 'radeon',
};

const PART_TYPES: Record<string, string> = {
  assy: 'assembly',
  assly: 'assembly',
  gskt: 'gasket',
  cyl: 'cylinder',
  brg: 'bearing',
  pstn: 'piston',
  piston: 'piston',
  plt: 'plate',
  clth: 'clutch',
  brk: 'brake',
  brake: 'brake',
  chn: 'chain',
  chain: 'chain',
  spkt: 'sprocket',
  sprocket: 'sprocket',
  vlv: 'valve',
  valve: 'valve',
  sttr: 'stator',
  stator: 'stator',
  cdi: 'cdi',
  coil: 'coil',
  carb: 'carburetor',
  carburettor: 'carburetor',
  mgnt: 'magneto',
  magneto: 'magneto',
  // Additional part types from real orders
  self: 'self start',
  selfs: 'self start',
  coolant: 'coolant',
  filter: 'filter',
  pad: 'pad',
  shoe: 'shoe',
  drum: 'drum',
  lever: 'lever',
  mirror: 'mirror',
  handle: 'handle',
  grip: 'grip',
  indicator: 'indicator',
  headlight: 'head light',
  bulb: 'bulb',
  wire: 'wire',
  cable: 'cable',
  switch: 'switch',
  horn: 'horn',
  meter: 'meter',
  speedo: 'speedometer',
  tank: 'tank',
  mudguard: 'mudguard',
  fender: 'fender',
  seat: 'seat',
  cover: 'cover',
  silencer: 'silencer',
  exhaust: 'exhaust',
  kick: 'kick',
  gear: 'gear',
  shaft: 'shaft',
  rotor: 'rotor',
  regulator: 'regulator',
  rectifier: 'rectifier',
  plug: 'plug',
  ring: 'ring',
  liner: 'liner',
  rod: 'rod',
  conrod: 'connecting rod',
  crank: 'crankshaft',
  cam: 'cam',
  rocker: 'rocker',
  tappet: 'tappet',
  timing: 'timing',
  oil: 'oil',
  seal: 'seal',
};

const SPECS: Record<string, string> = {
  fr: 'front',
  rr: 'rear',
  lh: 'left hand',
  rh: 'right hand',
  std: 'standard',
  stndrd: 'standard',
  dlx: 'deluxe',
  dlux: 'deluxe',
  spl: 'splendor',
  hh: 'hero honda',
};

/** Common misspellings and OCR-style confusions (0/O, 1/I, 8/B, etc.) */
const MISSPELLINGS: Record<string, string> = {
  acitva: 'activa',
  acteva: 'activa',
  actvla: 'activa',
  puslar: 'pulsar',
  plusr: 'pulsar',
  puisar: 'pulsar',
  dscover: 'discover',
  disover: 'discover',
  sp1endor: 'splendor',
  spendor: 'splendor',
  splendr: 'splendor',
  p1atina: 'platina',
  plat1na: 'platina',
  g1amour: 'glamour',
  glamor: 'glamour',
  glamur: 'glamour',
  sh1ne: 'shine',
  shinne: 'shine',
  un1corn: 'unicorn',
  pass1on: 'passion',
  passi0n: 'passion',
  jup1ter: 'jupiter',
  jupter: 'jupiter',
  jupitor: 'jupiter',
  apche: 'apache',
  break: 'brake',
  breke: 'brake',
  clutc: 'clutch',
  gaskit: 'gasket',
  beering: 'bearing',
  p1ston: 'piston',
  pist0n: 'piston',
  cy1inder: 'cylinder',
  va1ve: 'valve',
  sp0cket: 'sprocket',
  cha1n: 'chain',
  carburetor: 'carburetor',
  hero: 'hero',
  honda: 'honda',
  bajaj: 'bajaj',
  yamaha: 'yamaha',
  suzuki: 'suzuki',
};

/** Single flat map: token (lowercase) -> expansion (lowercase). Misspellings override abbreviations. */
function buildExpandMap(): Record<string, string> {
  const m: Record<string, string> = {};
  for (const [k, v] of Object.entries(VEHICLES)) m[k] = v;
  for (const [k, v] of Object.entries(PART_TYPES)) m[k] = v;
  for (const [k, v] of Object.entries(SPECS)) m[k] = v;
  for (const [k, v] of Object.entries(MISSPELLINGS)) m[k] = v;
  return m;
}

export const EXPAND_MAP = buildExpandMap();
